[versions]
workspace_version = "5.2.1.0"

#Define the library by defining its module and version reference.
[libraries]

#Gradle plugins should be defined here. WilderWorkspace is a gradle plugin.
[plugins]
workspace = { id = "com.wildermods.workspace", version.ref = "workspace_version" }
